### ISSUE TITLE
Set up GitHub Sponsors for this repo

### ISSUE THREAD

**Issue by andrasfuchs** [Nebukam/steam-game-finder#3]
Hi, I tried to donate some money to you within Firefox using ko-fi, but it would have forced me to register at PayPal, which I prefer not to do.

I think if you set up [GitHub Sponsors](https://github.com/sponsors) we might be able to give you financial support without PayPal ;)
There is a tutorial to set it up [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository).

**Comment by Nebukam** [comment]
Hah! Thanks a lot for the thought 🙏
I looked into GitHub sponsors but my understanding is that the project needs to be open source -- I released the steam app as MIT, not sure it would have value as a fully open source initiative (plus the extension accounts are linked to my personal email)

Actually just knowing you bothered checking has as much value as any money you would've sent ❤️

**Comment by andrasfuchs** [comment]
Sure thing!
